In [70]:
import numpy as np
# Type, Shape, Dimension에 대하여

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('\n array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


In [19]:
# print 쓰는 방법

print('{0} and {1}'.format('spam', 'eggs'))
print('{1} and {0}'.format('spam', 'eggs'))
 
num1=1;num2=2
print('{0} {1}'.format(num1,num2))

spam and eggs
eggs and spam
1 2


In [72]:
list1 = [1,2,3]
print(type(list1),list1)
# print(list1, list1.dtype) list는 data type이 없나..?
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3] int32


In [25]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(list2, array2, array2.dtype)

list3 = [1, 2, 3.09]
array3 = np.array(list3)
print(list3, array3, array3.dtype)

[1, 2, 'test'] ['1' '2' 'test'] <U11
[1, 2, 3.09] [1.   2.   3.09] float64


In [26]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float32')
print(array_int, array_int.dtype, array_float, array_float.dtype)



[1 2 3] int32 [1. 2. 3.] float32


In [29]:
sequence_array = np.arange(10)

print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [35]:
# zeros, ones

zero_array = np.zeros((3,2), dtype = 'int32')
one_array = np.ones((3,2), dtype = 'float32')
zero2_array = np.zeros((2,3))


print(zero_array, zero_array.dtype, zero_array.shape, '\n')
print(one_array, one_array.dtype, one_array.shape, '\n')
print(zero2_array, zero2_array.dtype, zero2_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]] float32 (3, 2) 

[[0. 0. 0.]
 [0. 0. 0.]] float64 (2, 3)


In [51]:
# arange랑 reshape쓰는법

array1 = np.arange(10)
print(array1,'\n')

array2 = array1.reshape(-1,5)
print(array2, '\n array2 shape : \n', array2.shape, '\n')

array3 = array1.reshape(5,-1)
print(array3, '\n array3 shape : \n', array3.shape)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 array2 shape : 
 (2, 5) 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 
 array3 shape : 
 (5, 2)


In [73]:
# reshape 쓰는법

array1d = np.arange(8) # np.arange(8) = 1,2,3 ... 7임 8아님
print('\n array1d list expression:', array1d.tolist())
print('\n array1d shape:', array1d.shape)

array3d = array1d.reshape((2,2,2))
print('\n array3d list expression:\n', array3d.tolist())
print('\n array3d : \n', array3d)
print('\n array3d shape:', array3d.shape)

# 3 Dimesions ndarray transform to 2D ndarray
array2D_1 = array3d.reshape(-1,1)
print('\n array2D_1 list expression :', array2D_1.tolist())
print('array2D_1 shape:', array2D_1.shape)

# 1D transfrom to 2D
array2D_2 = array1d.reshape(-1,1)
print('\n array2D_2 list expression :', array2D_2.tolist())
print('array2D_2 shape:', array2D_2.shape)





 array1d list expression: [0, 1, 2, 3, 4, 5, 6, 7]

 array1d shape: (8,)

 array3d list expression:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

 array3d : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

 array3d shape: (2, 2, 2)

 array2D_1 list expression : [[0], [1], [2], [3], [4], [5], [6], [7]]
array2D_1 shape: (8, 1)

 array2D_2 list expression : [[0], [1], [2], [3], [4], [5], [6], [7]]
array2D_2 shape: (8, 1)


In [66]:
# : 쓰는법

array1 = np.arange(start=1,stop=10) # start1, stop10 = 1,2,3 ... 9임 10 아님
print('array1 :',array1)
print('array1[1] :', array1[1])
print('array1[-1] :', array1[-1])

array1 : [1 2 3 4 5 6 7 8 9]
array1[1] : 2
array1[-1] : 9


In [69]:
array1 = np.arange(10) # 0 1 2 3 4 5 6 7 8 9
array4 = array1[3:5] # 3 4 5 일거 같지? 아님
array5 = array1[:3] # 0 1 2 3 일거 같지? 아님
array6 = array1[3:] # 3 4 5 6 7 8 9 일거 같지? 맞음 ㅎㅎㅎㅎㅎㅎ
array7 = array1[:]

print('array1 :', array1)
print('array4 :', array4)
print('array5 :', array5)
print('array6 :', array6)
print('array7 :', array7)

array1 : [0 1 2 3 4 5 6 7 8 9]
array4 : [3 4]
array5 : [0 1 2]
array6 : [3 4 5 6 7 8 9]
array7 : [0 1 2 3 4 5 6 7 8 9]


In [79]:
# boolean indexing

array1d = np.arange(start=1, stop=10)
print('array1d :',array1d)
array_boolean_indexing = array1d[array1d > 5]
print('array_boolean_indexing :',array_boolean_indexing)
print('array1d > 5 :', array1d > 5)
array1d>5 # 즉, array1d > 5 조건식의 반환인 ndarray 객체를 어떤 ndarray의 인덱싱 [] 안에 넣으면 True인 애들만 반환해준다

array1d : [1 2 3 4 5 6 7 8 9]
array_boolean_indexing : [6 7 8 9]
array1d > 5 : [False False False False False  True  True  True  True]


array([False, False, False, False, False,  True,  True,  True,  True])

In [94]:
# sort

org_array = np.array([3, 1, 9, 5])
print('Original Array :', org_array)
sort_array1 = np.sort(org_array)
print('\nnp.sort(org_array) :', sort_array1)
print('org_array :', org_array)

org_array = np.array([3, 1, 5, 9])
sort_array2 = org_array.sort() # org_array.sort 하고 괄호 안치면 output  
#Sorted by ndarray.sort output : <built-in method sort of numpy.ndarray object at 0x0000028E763EE850> 나옴 그리고 sorting 안댐
print('\norg_array.sort() :', sort_array2)
print('org_array :', org_array)

org_array = np.array([3, 1, 5, 9])
desc_array = np.sort(org_array)[::-1]
print('\n np.sort(org_array)[::-1] :', desc_array)
print('org_array :', org_array)
print('\n\n')

array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('Orignal Array :\n',array2d)
print('np.sort(array2d, axis=0) :\n', sort_array2d_axis0)
print('np.sort(array2d, axis=1) :\n', sort_array2d_axis1)

Original Array : [3 1 9 5]

np.sort(org_array) : [1 3 5 9]
org_array : [3 1 9 5]

org_array.sort() : None
org_array : [1 3 5 9]

 np.sort(org_array)[::-1] : [9 5 3 1]
org_array : [3 1 5 9]



Orignal Array :
 [[ 8 12]
 [ 7  1]]
np.sort(array2d, axis=0) :
 [[ 7  1]
 [ 8 12]]
np.sort(array2d, axis=1) :
 [[ 8 12]
 [ 1  7]]


In [95]:
# np.argsort()  sorting한 행렬에 대해 원본행렬의 인덱스를 얻어오는건데 나중에 쓸때 검색해서 보자

# np.dot(A,B) A B 행렬 곱
# np.transpose(A) A Transpose